[cmake]
    command = 'cmake'
    args = ['${workspaceFolder}']
[cmake.options]
    cwd = '${workspaceFolder}build'

[build]
    command = 'cmake'
    args = ['--build', '.', '-t', 'see']
[build.options]
    cwd = '${workspaceFolder}build'

[run]
    command = '${workspaceFolder}build/see'
    args = ['ls']
